---
logs:
  level: DEBUG
  token: ~
genomeprep:
  appId: urrutia-bismark_genome_preparation-0.18.1
  name: genome_prep
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    fasta: "agave://tacc-globalfs-urrutia/bismark/genome"
  notifications:
    -
      event: FAILED
      url: jawon@tacc.utexas.edu
bismark:
  appId: urrutia-bismark_app-0.1.0
  name: bismark_test
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    fastq1: ""
    genome_folder: "agave://tacc-globalfs-urrutia/bismark/genome"
  notifications:
    -
      event: FAILED
      url: jawon@tacc.utexas.edu
bme:
  appId: urrutia-bismark_methylation_extractor-0.18.1
  name: bme_test
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    bam: ""
    fasta: "agave://tacc-globalfs-urrutia/bismark/genome/TAIR.fa"
  parameters:
    paired: false
  notifications:
    -
      event: FAILED
      url: jawon@tacc.utexas.edu
bisukit:
  appId: urrutia-bisukit-0.1.3
  name: bisulkit_test
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    ot1: ""
    ot2: ""
    ob1: ""
    ob2: ""
    genome: "agave://tacc-globalfs-urrutia/bismark/genome/TAIR.fa"
  parameters:
    context: "CpG"
    cpg: 3
    input1: "sample1"
    qvalue: "0.01"
    diffmeth: 20
    input2: "sample2"
    dmc: 1
    specie: "TAIR"
  notifications:
    -
      event: FAILED
      url: jawon@tacc.utexas.edu
