---
logs:
  level: DEBUG
  token: ~
bismark:
  appId: urrutia-bismark_app-0.1.0
  name: bismark_test
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    fastq1: ""
    genome_folder: "agave://tacc-globalfs-urrutia/bismark/genome"
  notifications:
    -
      event: FAILED
      url: jawon@tacc.utexas.edu
